version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_management_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
